# Generated by Django 3.1.5 on 2021-02-02 13:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
                ('content', ckeditor.fields.RichTextField()),
                ('statu', models.CharField(choices=[('showing', 'Gösterimde'), ('prepared', 'Hazır'), ('unprepared', 'Hazırlanmamış')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
