# Generated by Django 3.1.5 on 2021-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayfa',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sayfa',
            name='statu',
            field=models.CharField(choices=[('unprepared', 'Hazırlanmamış'), ('showing', 'Gösterimde'), ('prepared', 'Hazır')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sayfa',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
