# Generated by Django 3.1.5 on 2021-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210202_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayfa',
            name='statu',
            field=models.CharField(choices=[('unprepared', 'Hazırlanmamış'), ('prepared', 'Hazır'), ('showing', 'Gösterimde')], max_length=15),
        ),
    ]
