# Generated by Django 3.1.5 on 2021-02-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsoru',
            name='content',
            field=models.CharField(choices=[('fraud', 'Sahtekarlık'), ('nudity', '+18'), ('spam', 'spam'), ('violence', 'Şiddet')], default='Seçilmemiş', max_length=15),
        ),
    ]
