# Generated by Django 3.1.5 on 2021-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportsoru_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsoru',
            name='content',
            field=models.CharField(choices=[('nudity', '+18'), ('violence', 'Şiddet'), ('spam', 'spam'), ('fraud', 'Sahtekarlık')], max_length=15),
        ),
    ]
