# Generated by Django 3.1.5 on 2021-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210202_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsoru',
            name='content',
            field=models.CharField(choices=[('fraud', 'Sahtekarlık'), ('notselect', '---Seçiniz---'), ('spam', 'spam'), ('nudity', '+18'), ('violence', 'Şiddet')], max_length=15),
        ),
    ]
