# Generated by Django 3.1 on 2021-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('economy', 'Ekonomi'), ('other', 'Diğer'), ('health', 'Sağlık'), ('sport', 'Spor'), ('education', 'Eğitim')], max_length=15),
        ),
    ]
