# Generated by Django 3.1 on 2021-01-05 21:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20210105_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('sport', 'Spor'), ('other', 'Diğer'), ('economy', 'Ekonomi'), ('education', 'Eğitim'), ('health', 'Sağlık')], max_length=15),
        ),
        migrations.AlterField(
            model_name='soru',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
