# Generated by Django 3.1 on 2021-01-05 21:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20210106_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('sport', 'Spor'), ('health', 'Sağlık'), ('education', 'Eğitim'), ('other', 'Diğer'), ('economy', 'Ekonomi')], max_length=15),
        ),
        migrations.AlterField(
            model_name='soru',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
