# Generated by Django 3.1 on 2021-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_auto_20210106_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begensoru',
            name='repSor',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('other', 'Diğer'), ('education', 'Eğitim'), ('economy', 'Ekonomi'), ('sport', 'Spor'), ('health', 'Sağlık')], max_length=15),
        ),
    ]
