# Generated by Django 3.1 on 2021-01-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_auto_20210106_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('education', 'Eğitim'), ('health', 'Sağlık'), ('economy', 'Ekonomi'), ('other', 'Diğer'), ('sport', 'Spor')], max_length=15),
        ),
    ]
