# Generated by Django 3.1 on 2021-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_auto_20210107_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('health', 'Sağlık'), ('education', 'Eğitim'), ('economy', 'Ekonomi'), ('other', 'Diğer'), ('sport', 'Spor')], max_length=15),
        ),
    ]
