# Generated by Django 3.1.5 on 2021-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0011_auto_20210112_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('sport', 'Spor'), ('economy', 'Ekonomi'), ('other', 'Diğer'), ('education', 'Eğitim'), ('health', 'Sağlık')], max_length=15),
        ),
    ]
