# Generated by Django 3.1.5 on 2021-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0012_auto_20210117_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('health', 'Sağlık'), ('economy', 'Ekonomi'), ('sport', 'Spor'), ('education', 'Eğitim'), ('other', 'Diğer')], max_length=15),
        ),
    ]
