# Generated by Django 3.1.5 on 2021-02-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0013_auto_20210117_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('education', 'Eğitim'), ('sport', 'Spor'), ('economy', 'Ekonomi'), ('health', 'Sağlık'), ('other', 'Diğer')], max_length=15),
        ),
    ]
