# Generated by Django 3.1.5 on 2021-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0014_auto_20210202_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('other', 'Diğer'), ('health', 'Sağlık'), ('economy', 'Ekonomi'), ('education', 'Eğitim'), ('sport', 'Spor')], max_length=15),
        ),
    ]
