# Generated by Django 3.1.5 on 2021-02-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0015_auto_20210202_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('education', 'Eğitim'), ('sport', 'Spor'), ('economy', 'Ekonomi'), ('other', 'Diğer'), ('health', 'Sağlık')], max_length=15),
        ),
    ]
