# Generated by Django 3.1.5 on 2021-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0016_auto_20210202_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('sport', 'Spor'), ('economy', 'Ekonomi'), ('other', 'Diğer'), ('health', 'Sağlık'), ('education', 'Eğitim')], max_length=15),
        ),
    ]
