# Generated by Django 3.1.5 on 2021-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0017_auto_20210202_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='catego',
            field=models.CharField(choices=[('other', 'Diğer'), ('sport', 'Spor'), ('health', 'Sağlık'), ('economy', 'Ekonomi'), ('education', 'Eğitim')], max_length=15),
        ),
    ]
