# Generated by Django 3.1 on 2021-01-12 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArkadasIstek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atal', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('alanKullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alanKullanici', to=settings.AUTH_USER_MODEL)),
                ('atanKullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atanKullanici', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
