# Generated by Django 3.1.5 on 2021-01-17 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arkadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkadasım',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkadas1_2', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('arkadas1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkadas1', to=settings.AUTH_USER_MODEL)),
                ('arkadas2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkadas2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
