# Generated by Django 3.1 on 2021-01-07 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogum_gunu', models.DateField(blank=True, null=True, verbose_name='Doğum Günü')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lokasyon')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğrafınız')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
